 
CREATE PROCEDURE [dbo].[USP_NEWSPAPERS_INSERT]
@NPR_PARENT_ID int,
@NPR_TITLE nvarchar(50),
@NPR_DESC nvarchar(255),
@NPR_URL nvarchar(500),
@NPR_LANG char(3)
AS
INSERT INTO SOURCES
([NPR_PARENT_ID]
,[NPR_TITLE]
,[NPR_DESC]
,[NPR_URL]
,[NPR_LANG]
)
VALUES
(@NPR_PARENT_ID,
@NPR_TITLE ,
@NPR_DESC ,
@NPR_URL ,
@NPR_LANG )

GO