<%@ Page Title="" Language="C#" MasterPageFile="~/about/about.Master" AutoEventWireup="true" CodeBehind="default.aspx.cs" Inherits="newsflippers.about._default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<h3>About Newsflippers.com</h3>
        Newsflippers.com site is completly generated by a list of selected news sources. 
            It has been noted that most of the online news readers waste immense amount of 
            time just by waiting the page to load yet struggling to find the relvent news to 
            them. Newsflippers.com −&nbsp;Make you flip through your news just like you 
        flipping through a newspaper hence making your online news reading simple, fast 
        and effective. Newsflippers.com is not just another news web site, it&#39;s a total 
        new experience. It&#39;s fast, easy and no local fonts required. 
        <h3>How it works ?</h3>
        Newsflippers.com site is generating webpage images from the news sources and 
            arranging them accordingly. Currently it&#39;s supporting only selected news 
            sources.&nbsp; 
        <br />
        <br />
        Report an Issue or suggest a new feature<br />
        <asp:TextBox CssClass="textbox" ID="TextBox1" runat="server" Height="71px" TextMode="MultiLine" 
            Width="558px"></asp:TextBox>
        <br /><br />
        <asp:LinkButton ID="LinkButton1" CssClass="btn" runat="server" ><span><span>Submit</span></span></asp:LinkButton>
        &nbsp;<asp:Label ID="lblMsg" runat="server"></asp:Label>
        <br />
</asp:Content>
